version: '3.8'
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/aoropeza/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/aoropeza/data/mariadb
      type: none

networks:
  inception:
    name: inception

services:
  #nginx:
  #container_name: nginx
  #build: ./requirements/nginx/
  #ports:
  #  - "443:443"
  #depends_on:
  #  - wordpress
  #volumes:
  #  - wordpress:/var/www/html
  #networks:
  #  - inception
  #restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volues:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"

